### PR TITLE
fix config issue with plugin instances in v.17

### PR DESCRIPTION
**Pull request by scambra**
move code to a class instantiated from bootstrap, so the config is got in bootstrap and passed to the class

I'm using this code, and the one from #18 and works with v1.17.5

### CODE REVIEW

**Comment by LucaProse** [comment]
Hi, can you explain in more detail how you solved it?
Thanks a lot

**Comment by scambra** [comment]
getConfig can be read only in bootstrap function, so moved all other functions to a different class, and created an instance, passing the config.

**Comment by LucaProse** [comment]
I am not a developer. How difficult is it to perform this process?

**Comment by scambra** [comment]
You can download my fork with git, and change to patch-1, which includes the fix.

git clone URL
git checkout patch-1

Then copy the directory to <ostickets_dir>/includes/plugins/

Or go to my fork in github (click the link 'scambra:patch-1') in the Pull Request header, and click Code, then Download zip, to download that branch.

**Comment by LucaProse** [comment]
It works perfectly. Thank you so much

**Comment by LucaProse** [comment]
There is only a little bug when i use the # in a new ticket stop working

**Comment by LucaProse** [comment]
Last question, when i create a new ticket with a collaborator he didn't recive an email of the new ticket opened. It's a probelm of my OsTicket configuration or a plugin error?

**Comment by scambra** [comment]
I just tested adding a collaborator on existing ticket, and sending mention. The fix worked to respect the settings so I could enabling or disabling the settings. I don't know if collaborator should get notification on new ticket, or if it's related to the ticket or is a osticket feature. I think the plugin only applies to add collaborator using @xxx in the replies or notes.

**Comment by LucaProse** [comment]
Ok, thank you so much

**Pull request merged**
